#pragma once

void test_locked_table_typedefs();
void test_locked_table_move();
void test_locked_table_unlock();
void test_locked_table_info();
void test_locked_table_clear();
void test_locked_table_insert_duplicate();
void test_locked_table_insert_new_key();
void test_locked_table_insert_lifetime();
void test_locked_table_erase();
void test_locked_table_find();
void test_locked_table_at();
void test_locked_table_operator_brackets();
void test_locked_table_count();
void test_locked_table_equal_range();
void test_locked_table_rehash();
void test_locked_table_reserve();
void test_locked_table_equality();
void test_locked_table_holds_locks_after_resize();
void test_locked_table_io();
void test_empty_locked_table_io();
